### ISSUE TITLE
typo of the name of the repo

### ISSUE THREAD

**Issue by n1c01a5** [asseth/ropsten-miner#1]
I think there is a typo of the name of the repo in the `readme` :
```
n1c0@debian-n1c0:/tmp$ cd ropten-miner
cd: The directory 'ropten-miner' does not exist
n1c0@debian-n1c0:/tmp$ cd ropsten-miner/
```

It's works with ```cd ropsten-miner/```

See https://github.com/asseth/ropsten-miner/pull/2

**Comment by kurthalex** [comment]
Thanks
